version: "3.3"
services:
  kafka:
    image: lensesio/fast-data-dev
    restart: unless-stopped
    environment:
      - ADV_HOST=240.12.0.2
      - RUNNING_SAMPLEDATA=0
      - RUNTESTS=0
      - CONNECT_PORT=0
    networks:
      statement:
        ipv4_address: 240.12.0.2

  elasticsearch:
    image: elasticsearch:7.10.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    networks:
      statement:
        ipv4_address: 240.12.0.3

  # grafana:
  #   image: grafana/grafana
  #   restart: unless-stopped
  #   networks:
  #     statement:
  #       ipv4_address: 240.12.0.4


  # prometheus:
  #   image: prom/prometheus
  #   restart: unless-stopped
  #   command: --config.file=/etc/prometheus/prometheus.yml
  #   volumes:
  #     - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     statement:
  #       ipv4_address: 240.12.0.5

  kibana:
    image: kibana:7.10.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://240.12.0.3:9200
      ELASTICSEARCH_HOSTS: http://240.12.0.3:9200
    depends_on:
    - "elasticsearch"
    networks:
      statement:
        ipv4_address: 240.12.0.6


networks:
  statement:
    driver: bridge
    ipam:
      config:
        - subnet: 240.12.0.0/29